---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bridge-token
  title: Bridge Token
  description: |-
    Bridge Token
  tags:
    - contract
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-connectors
  deployedAt: []
  interactsWith: []
  subcomponentOf: rainbow-token-connector
