---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bridge-token-on-near
  title: Bridge NEP-141 Token
  description: |-
    Bridged token represented as NEP-141 token contract
  tags:
    - contract
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-connectors
  deployedAt: []
  interactsWith: []
  subcomponentOf: rainbow-token-connector
