[package]
name = "silo-to-silo-integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora-sdk-integration-tests = { path = "aurora-sdk-integration-tests" }
serde = {version = "1", features = ["derive"] }
serde_json = "1"
