[package]
name = "silo-to-silo-integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora-sdk-integration-tests = { git = "https://github.com/aurora-is-near/aurora-contracts-sdk.git", branch = "silo" }
serde = {version = "1", features = ["derive"] }
serde_json = "1"
