steps:
    - label: "build all solidity contracts"
      command: |
          docker-compose up compile-solidity
          git status
          changed_files=$$(git status --porcelain --untracked-files=no | wc -l)
          if [ $$changed_files -gt 0 ]; then
            echo 'contract changed, please rebuild contract'
            exit 1
          fi

    - label: "test erc20-connector"
      command: |
          source ~/.yarn/yarn.sh
          cd erc20-connector
          yarn
          yarn test
