apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silo-to-silo
  title: SiloToSilo
  description: |-
    Facilitates transfers between silos
  tags:
    - contract
    - aurora
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-connectors
  deployedAt:
    - contract:aurora/mainnet/0x055707c67977e8217F98f19cFa8aca18B2282D0C
  subcomponentOf: rainbow-token-connector
