[package]
name = "aurora-engine-parameters"
version = "0.1.0"
edition = "2021"

[dependencies]
near-sdk = { git = "https://github.com/near/near-sdk-rs", rev = "613adcab6322e4f830efb4d5bde2a810ae642158" }