---
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "50 9 * * *"
  workflow_dispatch:

name: "Contract Security Analysis"
jobs:
  contract_analysis:
    name: "Shared"
    uses: aurora-is-near/.github/.github/workflows/security_analysis.yml@master
    secrets:
      DD_API_KEY: ${{secrets.DD_API_KEY}}
    with:
      ignore_failures: "true"
